### ISSUE TITLE
URL filepath

### ISSUE THREAD

**Issue by dfluegge** [anonimmety/model-107-manuals#1]
Nice work on the tool. On Windows OS, I just manually added the required libraries and didn't bother with the virtualenv. Running 'Download.py' I had an issue where the URL path to each file was incorrect, which in turn generated an invalid PDF file. It turns out that I had to add a '/' to the end of the base path:

base = "https://www.startekinfo.com/StarTek/outside/11883/PROGRAM/"

**Comment by anonimmety** [comment]
You're correct, I'll fix it. Thanks!
